version: "3.3"

services:
  api:
    build: ./
    command: bash -c "/migrate.sh; npm start"
    depends_on:
      - "db"
    links:
      - db:db
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
  db:
    env_file: config/.env
    image: mysql:5.7
    ports:
      - "33060:3306"
    restart: always          
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: