version: "3.3"

services:
  api:
    build: ./
    command: bash -c "/migrate.sh; nodemon ./src/app.ts"
    depends_on:
      - "db"
    links:
      - db:db
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      
  db:
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    image: mysql:5.7
    ports:
      - "33060:3306"
    restart: always          
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: 