version: 2
jobs:
  build:
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install Docker Compose
          command: |
            set -x
            apk update && apk add curl curl-dev bash
            apk add ca-certificates wget
            wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
            GLIBC_VERSION='2.27-r0' && \
                wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk && apk add glibc-${GLIBC_VERSION}.apk && \
                wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk && apk add glibc-bin-${GLIBC_VERSION}.apk                        
            curl -L https://github.com/docker/compose/releases/download/1.26.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - run:
          name: Copy config files
          command: |
            set -x
            cp config/test/.env.example config/test/.env

      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose -f scripts/general/docker-compose.yml -f scripts/ci/docker-compose.yml up --abort-on-container-exit