version: "3.3"

services:
  api:
    build:
     dockerfile: ./scripts/dev/Dockerfile
    command: bash -c "./scripts/migrate.sh; npm start"
    ports:
      - "3000:3000"    
    volumes:
      - ../../src:/usr/src/app/src      
  db:
    env_file: ../../config/dev/.env