openapi: 3.0.0
info:
  description: Conduit API
  version: 1.0.0
  title: Conduit API
  contact: 
    name: RealWorld
    url: https://realworld.io
  license: 
    name: MIT License
    url: https://opensource.org/licenses/MIT
schemes: [ https, http ]
produces: [ application/json ]
consumes: [ application/json ]
paths:
  /users:
      post:
        summary: Register a new user
        description: Register a new user
        tags: [ User and Authentication ]
        operationId: CreateUser
        requestBody:
          required: true
          description: Details of the new user to register
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewUserRequest"
        responses:
          "201":
            description: Created and returned new user
            content:
              aplication/json:
                schema:
                  $ref: "#/components/schemas/UserResponse"
          "422":
            description: Failed to create new user because they already exist or the request was bad
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/GenericErrorModel"
components:
  schemas:
    GenericErrorModel:
      type: object
      properties:
        errors:
          type: object
          properties:
            body:
              type: array
              items:
                type: string
          required: [
            body
          ]
      required: [
        errors
      ]
    User:
      type: object
      properties:
        email:
          type: string
        token: 
          type: string
        username: 
          type: string
        bio: 
          type: string
        image: 
          type: string
      required: [
        email,
        token,
        username,
        bio,
        image
      ]
    UserResponse: 
      type: object
      properties: 
        user: 
          $ref: "#/components/schemas/User"
      required: [
        user
      ]
    NewUserRequest:
      type: object
      properties: 
        user: 
          $ref: "#/components/schemas/NewUser"
      required: [
        user
      ]
    NewUser: 
      type: object
      properties: 
        username: 
          type: string
        email: 
          type: string
        password: 
          type: string
          format: password
      required: [
        username,
        email,
        password
      ]